### ISSUE TITLE
Plugin throws error in IDEA 15.0

### ISSUE THREAD

**Issue by kriegaex** [aefimov/idea-batch#17]
The plugin v1.0.4 worked in IDEA 14.1.5, but not anymore in 15.0. When trying to start a run config, the event log says:

    NoSuchMethodError: com.intellij.execution.configurations.GeneralCommandLine.setEnvParams(Ljava/util/Map;)V

**Comment by rafalmag** [comment]
I get the same issue, full stacktrace:
```
com.intellij.execution.configurations.GeneralCommandLine.setEnvParams(Ljava/util/Map;)V
java.lang.NoSuchMethodError: com.intellij.execution.configurations.GeneralCommandLine.setEnvParams(Ljava/util/Map;)V
	at org.intellij.lang.batch.runner.BatchCommandLineState.generateCommandLine(BatchCommandLineState.java:49)
	at org.intellij.lang.batch.runner.BatchCommandLineState.startProcess(BatchCommandLineState.java:29)
	at org.intellij.lang.batch.runner.BatchCommandLineState.startProcess(BatchCommandLineState.java:18)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:376)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:343)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by denis-bogdanas** [comment]
This plugin is not actively developed. You are welcome to submit a pull request with a fix.

**Comment by kriegaex** [comment]
Thanks for the merge.

Have you pushed a new release onto the public JetBrains plugin repo yet?

**Comment by aefimov** [comment]
Still no, try to build this one on this weekend...

**Comment by aefimov** [comment]
https://plugins.jetbrains.com/plugin/265

Alexander, if you wish i can add you as author on plugins.jetbrains.net, and you will be able to publish plugins as you need then.

**Comment by kriegaex** [comment]
Feel free to, thanks. :-)

**Comment by aefimov** [comment]
I need your login on plugins.jetbrains.net to add you :)

**Comment by kriegaex** [comment]
User name: kriegaex

**Comment by aefimov** [comment]
Done
